### ISSUE TITLE
Predictive Sort

### ISSUE THREAD

**Issue by zm-amblique** [taurgis/plugin_filternavigation#4]
Hi there

Sorry this is more a question than issue.
Are you able to let us know how this works with Predictive Sort?
Predictive Sort means product listings (PLP) sort order can change from request to request. And no caching is done on PLP.
In terms of "Go back to the PLP from a PDP without losing your location" - is Predictive Sort supported?

Zamil

**Comment by taurgis** [comment]
Hi,

This was written as a starting point, and I did not take predictive sorting into account. Since predictive sort will change with every request, you may return to a point on the page, but the product you were on is gone because it moved a few spots.

This is not a problem that is "easily" fixed, I'm afraid. The product might have even shifted a page.

**Comment by zm-amblique** [comment]
Got it, thank you.
